# Compile all C code.  Do not compile the FORTRAN versions.
library:
	( cd Source    ; $(MAKE) )

# remove object files, but keep the compiled programs and library archives
clean:
	( cd Source    ; $(MAKE) clean )



